MONGODB_URL_KEY="mongodb+srv://simranskills:<password>@cluster0.w8hdb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
AWS_ACCESS_KEY_ID="key"
AWS_SECRET_ACCESS_KEY="key"
AWS_DEFAULT_REGION="us-east-1"
MONGODB_URL="mongodb+srv://simranskills:<password>@cluster0.w8hdb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
